[theme]
primaryColor = "#4f46e5"              # Modern blue for buttons/accents
backgroundColor = "#f9fafb"           # Light subtle background
secondaryBackgroundColor = "#ffffff"  # White cards for inputs
textColor = "#111827"                 # Deep grey for readability
font = "sans serif"
